# NumPy

In [2]:
import numpy as np

In [3]:
# Create from list

# 1 D array
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr,type(arr), arr.shape)

# 2 D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2, arr2.shape)

[1 2 3 4 5 6] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


### Create with some functions

In [4]:
# dtype used to convert data type to int 
arr1 = np.zeros((2,3), dtype= "int64") #Prefill
print(arr1, arr1.shape)

arr2 = np.ones((2,3)) #Prefill
print(arr2, arr2.shape)

arr3 = np.full((2,3), 100) #Prefill with a particular value
print(arr3, arr3.shape)

arr4 = np.eye(3) # Creates a identity matrix
print(arr4 , arr4.shape)

arr5 = np.arange(0, 11, 2) # Range elements
arr5

arr6 = np.linspace(1, 100, 4) # Creates a array with even spaces
arr6



[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


array([  1.,  34.,  67., 100.])

### Properties

In [5]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

print(arr.shape)  # Dimensions m * n
print(arr.size)   # Gives total elements
print(arr.dtype)  # Gives data type
print(arr.ndim)   # Gives number of dimensions 

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 2)
6
int64
2
[[1. 2.]
 [3. 4.]
 [5. 6.]] float64


### Operations on array

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

# Changing dimensions
reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

# Flattning array => conevrting array in one dimensional
flatten = arr.flatten()
print(flatten, flatten.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


### Indexing

In [7]:
# Indexing on 1-D array
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])
print(arr[4])

# Indexing on 2-D array

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[1][1])
print(arr2[0][2])

1
5
5
3


In [8]:
# Fancy indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0 , 2, 3]
print(arr[idx])

[1 3 4]


In [9]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


### Slicing Operations

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr[2:4])
print(arr[1:])
print(arr[:2])

[3 4]
[2 3 4 5 6]
[1 2]


### Data Types

In [18]:
# Integers
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)

# Float
arr1 = np.array([1, 2.32, 3, 4, 5])
print(arr1, arr1.dtype)

# String
arr2 = np.array([1, 2.32, 3, 4, 5, "prime"])
print(arr2, arr2.dtype)

# Complex values
arr3 = np.array( 3 + 5j)
print(arr3, arr3.dtype)

[1 2 3 4 5] int64
[1.   2.32 3.   4.   5.  ] float64
['1' '2.32' '3' '4' '5' 'prime'] <U32
(3+5j) complex128


### Multi-dimensional arrays

In [22]:
# 2-D array
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr2d)

# Sum of whole matrix
print(np.sum(arr2d))

# Sum of columns
print(np.sum(arr2d, axis=0))

# Sum of rows
print(np.sum(arr2d, axis = 1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
[15 18 21 24]
[10 26 42]
